### PR TITLE
Ci | auto publish RVPS and AS image

### LINKED ISSUE #87: CI | Automatic release scripts
We need automatic release scripts to publish the images when cutting releases.

### PR DESCRIPTION
**Pull request by Xynnn007**
Close #87

### CODE REVIEW

**Comment by Xynnn007** [comment]
cc @jepio

**Review by jepio — APPROVED** [review]
Cool, later we can improve it to take the label from git tag, etc.

**Comment by Xynnn007** [comment]
Update: make the CI automatically triggered by a new release

**Review by jialez0 — APPROVED** [review]
LGTM.

**Pull request merged**
