### PR TITLE
TDX Verifier: Add fine grained parsed claims inside evidence

### PR DESCRIPTION
**Pull request by Xynnn007**
cc @jialez0 
Please take a look if it is suitable

### CODE REVIEW

**Comment by Xynnn007** [comment]
Note that there are two kinds of kernel parameters due to https://www.kernel.org/doc/html/v4.14/admin-guide/kernel-parameters.html:
- `A=B` style, like `console=hvc0`. Serialized to a key-value pair `"A":"B"` in JSON.
- `A` style, like `hw`. Serialized to a key-value pair with `null` value in JSON, s.t. `"A": null`

I handle the both in a `Map`, the format will look lile
```json
"kernel_parameters": {
    "console": "hvc0",
    "hw": null
}
```

If a parameter is `A=`, then we will serialize that into `"A": ""`, here the value is an empty string rather than `null`

**Review by sameo — APPROVED** [review]

**Comment by jialez0** [comment]
@sameo Can we reverse this PR for now? Because if we merged this now, the OPA default policy can not parse the new format claims, this will cause the validation of the policy engine failure. Could we wait for this PR to add modifications to the default policy before merging it? So sorry for didn't remind that...

**Comment by jialez0** [comment]
@sameo BTW, I think we should merge PR #106  with higher priority as it solves the problem of current AS being unable to verify evidence of real TDX hardware platform.

**Comment by jialez0** [comment]
@Xynnn007 WDYT?

**Comment by Xynnn007** [comment]
Yes. Related code is not prepared in the policy engine side. A better way is to revert this PR and wait for all other things are ok. Let me write an issue to track this.

**Comment by Xynnn007** [comment]
Let me make another PR to provide a workaround. Better ways can be discussed in future

**Pull request merged**
