### PR TITLE
AS: Add basic compile testing

### PR DESCRIPTION
**Pull request by liangzhou121**
1.Enable the basic compile check for AS.
2.Fixed some warning errors that were detected by the `cargo fmt --all -- --check` and `cargo clippy -- -D warnings`.

Fixes: #5
Signed-off-by: zhouliang121 <liang.a.zhou@linux.alibaba.com>

### CODE REVIEW

**Review by jodh-intel — COMMENTED** [review]
Thanks @liangzhou121. Could you chagne the commit to explain the other changes? Presumably fixes related to clippy?

**Comment by liangzhou121** [comment]
> Thanks @liangzhou121. Could you chagne the commit to explain the other changes? Presumably fixes related to clippy?

Yes, these other changes are to fix these warning errors that were detected by the `cargo fmt --all -- --check` and `cargo clippy -- -D warnings`. I will update the commit message also.

**Review by fitzthum — APPROVED** [review]
LGTM. Ideally this might be multiple commits.

**Review by sameo — APPROVED** [review]
LGTM. This could have been split into 2 separate commits, but that's fine.

**Pull request merged**
