### PR TITLE
Fix Azure SNP vTPM attestation (grpc)

### PR DESCRIPTION
**Pull request by lmilleri**
Fix attestation in the case of Azure SNP vTPM

### CODE REVIEW

**Comment by fitzthum** [comment]
Should be easy to get this merged, but is this required for v0.8.0? Otherwise it might be best to wait a day or two.

**Comment by ariel-adam** [comment]
Not critical for 0.8.0

**Comment by fitzthum** [comment]
Can you open the same PR against the KBS repo? We can get it merged ASAP over there.

**Comment by lmilleri** [comment]
Already merged to main branch in kbs. Thanks.

https://github.com/confidential-containers/kbs/pull/221

**Pull request closed without merging**
